# 端口号配置
server:
  port: 8080

spring:
  redis:
    host: 39.101.78.244
    port: 6379
    password: root
    database: 0 # 几号库
    lettuce:
      pool:
        max-active: 8 # 最大连接
        max-idle: 8 # 最大空闲连接
        min-idle: 0 # 最小空闲连接
        max-wait: 1000ms # 连接等待时间

#logging:
#  level:
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
logging:
  level:
    com.mk: debug